// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4o7wdaT9o8yivN-0vopkJnCL3sd4FGc',
    appId: '1:459941913422:web:819a0a4e8926ffece8741f',
    messagingSenderId: '459941913422',
    projectId: 'fatec-pdm-app06-loja-cafe',
    authDomain: 'fatec-pdm-app06-loja-cafe.firebaseapp.com',
    storageBucket: 'fatec-pdm-app06-loja-cafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKoYcEE3pGglT2-cfisCLjvEjOoXtSpsQ',
    appId: '1:459941913422:android:e5985575e2f23d65e8741f',
    messagingSenderId: '459941913422',
    projectId: 'fatec-pdm-app06-loja-cafe',
    storageBucket: 'fatec-pdm-app06-loja-cafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8ExpwZIAys8EmGBU7ke5xZYRPmBhLFU',
    appId: '1:459941913422:ios:e972b51e5045de0de8741f',
    messagingSenderId: '459941913422',
    projectId: 'fatec-pdm-app06-loja-cafe',
    storageBucket: 'fatec-pdm-app06-loja-cafe.appspot.com',
    iosClientId: '459941913422-omggaceiqrdemur8s3f3hjn101641kt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app06',
  );
}
